# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aether_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(824, 924)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 751, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_lumapi = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_lumapi.setObjectName("lineEdit_lumapi")
        self.gridLayout_3.addWidget(self.lineEdit_lumapi, 0, 1, 1, 1)
        self.pushButton_browse = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout_3.addWidget(self.pushButton_browse, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 811, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.FDTD = QtWidgets.QWidget()
        self.FDTD.setObjectName("FDTD")
        self.groupBox_5 = QtWidgets.QGroupBox(self.FDTD)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 230, 801, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.Files_List = QtWidgets.QTableWidget(self.groupBox_5)
        self.Files_List.setGeometry(QtCore.QRect(10, 50, 781, 101))
        self.Files_List.setObjectName("Files_List")
        self.Files_List.setColumnCount(0)
        self.Files_List.setRowCount(0)
        self.lineEdit_data_folder = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_data_folder.setGeometry(QtCore.QRect(99, 20, 261, 22))
        self.lineEdit_data_folder.setObjectName("lineEdit_data_folder")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(20, 17, 107, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.data_browse = QtWidgets.QPushButton(self.groupBox_5)
        self.data_browse.setGeometry(QtCore.QRect(368, 19, 81, 25))
        self.data_browse.setObjectName("data_browse")
        self.groupBox = QtWidgets.QGroupBox(self.FDTD)
        self.groupBox.setGeometry(QtCore.QRect(530, 0, 261, 231))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_Parasit = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_Parasit.setFont(font)
        self.checkBox_Parasit.setObjectName("checkBox_Parasit")
        self.gridLayout.addWidget(self.checkBox_Parasit, 2, 0, 1, 1)
        self.checkBox_Mesh = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Mesh.setObjectName("checkBox_Mesh")
        self.gridLayout.addWidget(self.checkBox_Mesh, 4, 0, 1, 1)
        self.checkBox_Gen = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_Gen.setFont(font)
        self.checkBox_Gen.setObjectName("checkBox_Gen")
        self.gridLayout.addWidget(self.checkBox_Gen, 1, 0, 1, 1)
        self.checkBox_EQE = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_EQE.setFont(font)
        self.checkBox_EQE.setObjectName("checkBox_EQE")
        self.gridLayout.addWidget(self.checkBox_EQE, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox.setDecimals(6)
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(1e-06)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 0, 1, 1)
        self.checkBox_export_charge = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_export_charge.setObjectName("checkBox_export_charge")
        self.gridLayout.addWidget(self.checkBox_export_charge, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.FDTD)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 430, 801, 271))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.Results_List = QtWidgets.QTableWidget(self.groupBox_3)
        self.Results_List.setGeometry(QtCore.QRect(10, 30, 781, 211))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Results_List.setFont(font)
        self.Results_List.setDragEnabled(False)
        self.Results_List.setObjectName("Results_List")
        self.Results_List.setColumnCount(0)
        self.Results_List.setRowCount(0)
        self.pushButton_start = QtWidgets.QPushButton(self.FDTD)
        self.pushButton_start.setGeometry(QtCore.QRect(0, 720, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.groupBox_6 = QtWidgets.QGroupBox(self.FDTD)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 10, 461, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 107, 22))
        self.label_4.setObjectName("label_4")
        self.lineEdit_Mat_CIGS = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Mat_CIGS.setGeometry(QtCore.QRect(123, 110, 328, 22))
        self.lineEdit_Mat_CIGS.setReadOnly(False)
        self.lineEdit_Mat_CIGS.setObjectName("lineEdit_Mat_CIGS")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 48, 107, 22))
        self.label_3.setObjectName("label_3")
        self.lineEdit_Substr_M = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Substr_M.setGeometry(QtCore.QRect(123, 48, 328, 22))
        self.lineEdit_Substr_M.setReadOnly(False)
        self.lineEdit_Substr_M.setObjectName("lineEdit_Substr_M")
        self.lineEdit_CIGS_M = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_CIGS_M.setGeometry(QtCore.QRect(123, 20, 328, 22))
        self.lineEdit_CIGS_M.setReadOnly(False)
        self.lineEdit_CIGS_M.setObjectName("lineEdit_CIGS_M")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 107, 22))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Reflection_M = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Reflection_M.setGeometry(QtCore.QRect(123, 80, 328, 22))
        self.lineEdit_Reflection_M.setReadOnly(False)
        self.lineEdit_Reflection_M.setObjectName("lineEdit_Reflection_M")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 107, 22))
        self.label_10.setObjectName("label_10")
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.pushButton_start.raise_()
        self.tabWidget.addTab(self.FDTD, "")
        self.CHARGE = QtWidgets.QWidget()
        self.CHARGE.setObjectName("CHARGE")
        self.groupBox_2 = QtWidgets.QGroupBox(self.CHARGE)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 270, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_Auto_Charge = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_Auto_Charge.setFont(font)
        self.checkBox_Auto_Charge.setObjectName("checkBox_Auto_Charge")
        self.verticalLayout_2.addWidget(self.checkBox_Auto_Charge)
        self.checkBox_Force_Gen = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Force_Gen.setObjectName("checkBox_Force_Gen")
        self.verticalLayout_2.addWidget(self.checkBox_Force_Gen)
        self.groupBox_7 = QtWidgets.QGroupBox(self.CHARGE)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 10, 811, 261))
        self.groupBox_7.setObjectName("groupBox_7")
        self.Files_List_CSV = QtWidgets.QTableWidget(self.groupBox_7)
        self.Files_List_CSV.setGeometry(QtCore.QRect(10, 50, 791, 191))
        self.Files_List_CSV.setObjectName("Files_List_CSV")
        self.Files_List_CSV.setColumnCount(0)
        self.Files_List_CSV.setRowCount(0)
        self.lineEdit_data_CSV = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_data_CSV.setGeometry(QtCore.QRect(69, 20, 621, 22))
        self.lineEdit_data_CSV.setObjectName("lineEdit_data_CSV")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(10, 19, 107, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.data_browse_CSV = QtWidgets.QPushButton(self.groupBox_7)
        self.data_browse_CSV.setGeometry(QtCore.QRect(700, 20, 81, 25))
        self.data_browse_CSV.setObjectName("data_browse_CSV")
        self.groupBox_8 = QtWidgets.QGroupBox(self.CHARGE)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 310, 461, 171))
        self.groupBox_8.setObjectName("groupBox_8")
        self.Files_List_CHARGE = QtWidgets.QTableWidget(self.groupBox_8)
        self.Files_List_CHARGE.setGeometry(QtCore.QRect(0, 50, 451, 111))
        self.Files_List_CHARGE.setObjectName("Files_List_CHARGE")
        self.Files_List_CHARGE.setColumnCount(0)
        self.Files_List_CHARGE.setRowCount(0)
        self.data_browse_CHARGE_Process = QtWidgets.QPushButton(self.groupBox_8)
        self.data_browse_CHARGE_Process.setGeometry(QtCore.QRect(369, 19, 81, 25))
        self.data_browse_CHARGE_Process.setObjectName("data_browse_CHARGE_Process")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_sims_CHARGE_Process = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_sims_CHARGE_Process.setGeometry(QtCore.QRect(100, 20, 261, 22))
        self.lineEdit_sims_CHARGE_Process.setObjectName("lineEdit_sims_CHARGE_Process")
        self.groupBox_9 = QtWidgets.QGroupBox(self.CHARGE)
        self.groupBox_9.setGeometry(QtCore.QRect(-10, 480, 811, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setFlat(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.Results_List_CHARGE = QtWidgets.QTableWidget(self.groupBox_9)
        self.Results_List_CHARGE.setGeometry(QtCore.QRect(10, 30, 801, 211))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Results_List_CHARGE.setFont(font)
        self.Results_List_CHARGE.setDragEnabled(False)
        self.Results_List_CHARGE.setObjectName("Results_List_CHARGE")
        self.Results_List_CHARGE.setColumnCount(0)
        self.Results_List_CHARGE.setRowCount(0)
        self.pushButton_start_CHARGE = QtWidgets.QPushButton(self.CHARGE)
        self.pushButton_start_CHARGE.setGeometry(QtCore.QRect(0, 730, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_start_CHARGE.setFont(font)
        self.pushButton_start_CHARGE.setObjectName("pushButton_start_CHARGE")
        self.groupBox_11 = QtWidgets.QGroupBox(self.CHARGE)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 260, 461, 51))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_sims_CHARGE_BLUEPRINT = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_sims_CHARGE_BLUEPRINT.setGeometry(QtCore.QRect(100, 20, 261, 22))
        self.lineEdit_sims_CHARGE_BLUEPRINT.setObjectName("lineEdit_sims_CHARGE_BLUEPRINT")
        self.data_browse_CHARGE_BLUEPRINT = QtWidgets.QPushButton(self.groupBox_11)
        self.data_browse_CHARGE_BLUEPRINT.setGeometry(QtCore.QRect(369, 19, 81, 25))
        self.data_browse_CHARGE_BLUEPRINT.setObjectName("data_browse_CHARGE_BLUEPRINT")
        self.pushButton_process_charge = QtWidgets.QPushButton(self.CHARGE)
        self.pushButton_process_charge.setGeometry(QtCore.QRect(110, 730, 111, 31))
        self.pushButton_process_charge.setObjectName("pushButton_process_charge")
        self.tabWidget.addTab(self.CHARGE, "")
        self.tabWidget.raise_()
        self.groupBox_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aether"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Configuration:"))
        self.label.setText(_translate("MainWindow", "Python API:"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Files to Process:"))
        self.label_5.setText(_translate("MainWindow", "Data Folder:"))
        self.data_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox.setTitle(_translate("MainWindow", "FDTD Processing"))
        self.checkBox_Parasit.setText(_translate("MainWindow", "Substrate Parasitic EQE"))
        self.checkBox_Mesh.setText(_translate("MainWindow", "Export Mesh per Volume"))
        self.checkBox_Gen.setText(_translate("MainWindow", "Export CIGS Generation"))
        self.checkBox_EQE.setText(_translate("MainWindow", "CIGS EQE"))
        self.checkBox_export_charge.setText(_translate("MainWindow", "Export Model Variables"))
        self.label_7.setText(_translate("MainWindow", "Index Error Tolerance:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results:"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.groupBox_6.setTitle(_translate("MainWindow", "FDTD Settings:"))
        self.label_4.setText(_translate("MainWindow", "CIGS Material:"))
        self.label_3.setText(_translate("MainWindow", "Substrate Monitor:"))
        self.label_2.setText(_translate("MainWindow", "CIGS Monitor:"))
        self.label_10.setText(_translate("MainWindow", "Reflection Monitor:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FDTD), _translate("MainWindow", "FDTD"))
        self.groupBox_2.setTitle(_translate("MainWindow", "CHARGE Processing"))
        self.checkBox_Auto_Charge.setText(_translate("MainWindow", "Import model data from FDTD"))
        self.checkBox_Force_Gen.setText(_translate("MainWindow", "Force Generation File Loading"))
        self.groupBox_7.setTitle(_translate("MainWindow", "FDTD Import Data"))
        self.label_6.setText(_translate("MainWindow", "CSV file:"))
        self.data_browse_CSV.setText(_translate("MainWindow", "Browse"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Load Sims to Process"))
        self.data_browse_CHARGE_Process.setText(_translate("MainWindow", "Browse"))
        self.label_9.setText(_translate("MainWindow", "Sims Location:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Results:"))
        self.Results_List_CHARGE.setSortingEnabled(True)
        self.pushButton_start_CHARGE.setText(_translate("MainWindow", "Setup and Run"))
        self.groupBox_11.setTitle(_translate("MainWindow", "CHARGE Blueprint:"))
        self.label_8.setText(_translate("MainWindow", "Blueprint File:"))
        self.data_browse_CHARGE_BLUEPRINT.setText(_translate("MainWindow", "Browse"))
        self.pushButton_process_charge.setText(_translate("MainWindow", "Process Sim Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CHARGE), _translate("MainWindow", "CHARGE"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Configuration"))
        self.actionSave.setText(_translate("MainWindow", "Save Configuration"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
